version: "3"
services:
    rest-api:
        build: ./rest-api
        container_name: rest-api
        restart: on-failure
        depends_on:
            - redis
            - db
        env_file: ./rest-api/.env
        # TODO erase ports. only use for tests
        ports:
            - 5001:5000
    ws-api:
        build: ./ws-api
        container_name: ws-api
        restart: on-failure
        depends_on:
            - redis
        env_file: ./rest-api/.env
    celery-worker:
        build: ./celery-worker
        container_name: celery-worker
        restart: on-failure
        user: nobody
        depends_on:
            - redis
        env_file: ./celery-worker/.env
    frontend:
        build: ./frontend
        container_name: frontend
        restart: on-failure
        depends_on:
            - rest-api
            - ws-api
    nginx:
        image: nginx:alpine
        container_name: LBA
        restart: on-failure
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - 80:80
        depends_on:
            - rest-api
            - ws-api
            - frontend
    db:
        image: postgres:12-alpine
        container_name: postgres
        restart: on-failure
        volumes:
            - /postgres-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        env_file: ./database/db.conf
    redis:
        image: redis:4-alpine
        container_name: redis_queue
        restart: on-failure
        ports:
            - 6379:6379