version: "3"
services:
    backend:
        build: ./backend
        container_name: backend
        restart: on-failure
        depends_on:
            - redis
            - db
        env_file: ./backend/.env
    celery_worker:
        build: ./celery_worker
        container_name: celery_worker
        restart: on-failure
        user: nobody
        depends_on:
            - redis
            - backend
        env_file: ./celery_worker/.env
    db:
        image: postgres:12-alpine
        container_name: postgres
        restart: on-failure
        ports:
            - 5432:5432
        env_file: ./database/db.conf
    redis:
        image: redis:4-alpine
        container_name: redis_queue
        restart: on-failure
        ports:
            - 6379:6379
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: on-failure
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./web/dist:/usr/share/nginx/html
        ports:
            - 80:80
        depends_on:
            - backend

volumes:
  data: